models:
  - MiniCPM: 
      model_id: OpenBMB/MiniCPM-2B-sft-fp32
      revision: master

  - BaiChuan:
      model_id: baichuan-inc/Baichuan2-7B-Chat
      revision: v1.0.4

  - GLM4:
      model_id: ZhipuAI/glm-4-9b-chat
      revision: master

  - qwen2:
      model_id: qwen/Qwen2-7B-Instruct
      revision: master

  - LLaMA3:
      model_id: LLM-Research/Meta-Llama-3-8B-Instruct
      revision: master
